apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: [[forms[0].name]]
  name: [[forms[0].name]]
[[ forms[0].namespace ? "  namespace: " + forms[0].namespace + "\n" : ""]]
spec:
  replicas: 1
  selector:
    matchLabels:
      app: [[forms[0].name]]
  template:
    metadata:
      labels:
        app: [[forms[0].name]]
    spec:
      containers:
        - image: [[forms[0].image]]
          name: [[forms[0].name]]